name: Daily Check

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-zou-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Install zou
      run: pip install --no-dependencies zou

    - name: Check Zou Package Version
      run: |
        # Get each variable
        LATEST_VERSION=$(cat latest-version.txt)
        ZOU_VERSION=$(pip show zou | grep Version | awk '{print $2}')
        if [ "$LATEST_VERSION" != "$ZOU_VERSION" ]; then
          # Write the latest version to .txt
          echo "Updating latest-version.txt to $ZOU_VERSION"
          echo "$ZOU_VERSION" > latest-version.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add latest-version.txt
          git commit -m "Update latest-version.txt to $ZOU_VERSION"
          git push
          # Build docker image
          echo "New version found! $ZOU_VERSION"
          echo "Building new docker image"
          echo "BUILD=True" >> $GITHUB_ENV
          echo "ZOU_VERSION=$ZOU_VERSION" >> $GITHUB_ENV
        else
          echo "No update found"
          echo "BUILD=False" >> $GITHUB_ENV
        fi
    - name: Trigger docker-publish.yml
      run: |
        if [[ "${{ env.BUILD }}" == "True" ]]; then
          echo "BUILD is set to True"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/EmberLightVFX/Zou-for-Docker/dispatches \
            --data '{"event_type": "docker-publish", "client_payload": {"ZOU_VERSION": "${{ env.ZOU_VERSION }}"}}'
        else
          echo "BUILD is not set to True"
        fi